[versions]
# libraries
junit = "4.13.2"
pmd = "7.16.0"

# plugins
changelog = "2.2.1"
intelliJPlatform = "2.9.0"
kotlin = "2.2.0"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
pmd-core = { group = "net.sourceforge.pmd", name = "pmd-core", version.ref = "pmd" }
pmd-apex = { group = "net.sourceforge.pmd", name = "pmd-apex", version.ref = "pmd" }
pmd-visualforce = { group = "net.sourceforge.pmd", name = "pmd-visualforce", version.ref = "pmd" }
pmd-java = { group = "net.sourceforge.pmd", name = "pmd-java", version.ref = "pmd" }
pmd-javascript = { group = "net.sourceforge.pmd", name = "pmd-javascript", version.ref = "pmd" }
pmd-kotlin = { group = "net.sourceforge.pmd", name = "pmd-kotlin", version.ref = "pmd" }
pmd-xml = { group = "net.sourceforge.pmd", name = "pmd-xml", version.ref = "pmd" }

[bundles]
pmd = ["pmd-core", "pmd-apex", "pmd-visualforce", "pmd-java", "pmd-javascript", "pmd-kotlin", "pmd-xml"]

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
intelliJPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intelliJPlatform" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
