[versions]
# libraries
junit = "4.13.2"
pmd = "7.19.0"

# plugins
changelog = "2.4.0"
intelliJPlatform = "2.10.4"
kotlin = "2.2.20"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
pmd-core = { group = "net.sourceforge.pmd", name = "pmd-core", version.ref = "pmd" }
pmd-java = { group = "net.sourceforge.pmd", name = "pmd-java", version.ref = "pmd" }
pmd-kotlin = { group = "net.sourceforge.pmd", name = "pmd-kotlin", version.ref = "pmd" }

[bundles]
pmd = ["pmd-core", "pmd-java", "pmd-kotlin"]

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
intelliJPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intelliJPlatform" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
